spring:
  application:
    name: chat-service

eureka:
  instance:
    #hostname: 192.168.0.146
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      #defaultZone: http://41.78.80.108:8761/eureka/
      defaultZone : http://localhost:8761/eureka/

server:
  port: 8985
  address: 0.0.0.0
