spring:
  application:
    name: chat-service
  config:
    import: secrets.properties
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  datasource:
    url: ${DATABASE_URL_DEV}
    username: ${DATABASE_USER_DEV}
    password: ${DATABASE_PASSWORD_DEV}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


eureka:
  instance:
    #hostname: 192.168.0.146
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      #defaultZone: http://41.78.80.108:8761/eureka/
      defaultZone : http://localhost:8761/eureka/


server:
  port: 8985
  address: 0.0.0.0
