eureka:
  instance:
    hostname: localhost
    #hostname: 41.78.80.108
    prefer-ip-address: false
    #prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761
  address: 0.0.0.0


