server:
  port: 8004

spring:
  application:
    name: NOTIFICATION-SERVICE
  datasource:
    url: ${DATABASE_URL_DEV}
    username: ${DATABASE_USER_DEV}
    password: ${DATABASE_PASSWORD_DEV}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: secrets.properties
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  pulsar:
    client:
      url: pulsar://localhost:6650


#mail:
#  host: ${SPRING_MAIL_HOST}
#  port: ${SPRING_MAIL_PORT}
#  username: ${SPRING_MAIL_USERNAME}|cbos tnbf yruz dglu
#  password: ${SPRING_MAIL_PASSWORD}
#  protocol: ${SPRING_MAIL_PROTOCOL}
#  properties:
#    mail.smtp.auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
#    mail.smtp.ssl.enable: ${MAIL_SMTP_SSL_ENABLE}
#    mail.smtp.socketFactory.port: ${MAIL_SMTP_SOCKETFACTORY_PORT}
#    mail.smtp.socketFactory.class: ${MAIL_SMTP_SOCKETFACTORY_CLASS}


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/