server:
  port: 8083

#rsa:
#  public-key: classpath:keys/publicKey.pem
#  private-key: classpath:keys/privateKey.pem
jwt:
  secret: ${JWT_SECRET}

spring:
  config:
    import: secrets.properties
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/mail/**
          filters:
            - AuthenticationFilter

  application:
    name: API-GATEWAY

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/



