server:
  port: 80811

#rsa:
#  public-key: classpath:keys/publicKey.pem
#  private-key: classpath:keys/privateKey.pem
jwt:
#  secret: ${JWT_SECRET}

spring:
  config:
    import: secrets.properties
  cloud:
    gateway:
      routes:
        - id: user-service-1
          uri: lb://USER-SERVICE
#          uri: http://localhost:8982
          predicates:
            - Path=/api/roles/**
          filters:
            - AuthenticationFilter

        - id: user-service-2
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/register
          filters:
            - AuthenticationFilter

        - id: user-service-3
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/login
          filters:
            - AuthenticationFilter

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/mail/**
          filters:
            - AuthenticationFilter

        - id: user-message-resend
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/resend-verification
          filters:
            - AuthenticationFilter

  application:
    name: API-GATEWAY
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: DEBUG



