spring:
  application:
    name: order-service
  config:
    import: secrets.properties
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  pulsar:
    client:
      service-url: pulsar://localhost:6650


  datasource:
    url: ${DATABASE_URL_DEV}
    username: ${DATABASE_USER_DEV}
    password: ${DATABASE_PASSWORD_DEV}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


eureka:
  instance:
    #hostname: 192.168.0.146
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      #defaultZone: http://41.78.80.108:8761/eureka/
       defaultZone : http://localhost:8761/eureka/


services:
  vendor-service:
    url: http://localhost:8983
  user-service:
    url: http://localhost:8982
server:
  port: 8986
  address: 0.0.0.0