server:
  port: 8081  # Gateway's port
  address: 0.0.0.0

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable discovery-based routing
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: user-auth-login
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/login

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth2/**

        - id: user-dashboard-redirect
          uri: lb://USER-SERVICE
          predicates:
            - Path=/dashboard-redirect

        - id: user-register
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/register

        - id: user-verify
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/verify

        - id: user-test-email
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/test-email

        - id: user-reset-password
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/reset-password

        - id: user-add-roles
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/roles/AddRoles

        - id: user-role-all
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/roles/allRoles

        - id: user-forgot-password
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/forgot-password

        - id: user-add-role-update
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/add-role

        - id: status-add
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/statuses/addStatus

        - id: buyer-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/buyer/**

        - id: status-view-all
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/statuses/viewAllStatus

        - id: status-view-single
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/statuses/get/{id}

        - id: status-update
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/statuses/update/{id}

        - id: status-delete
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/statuses/delete/{id}

        - id: market-add
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/markets/add

        - id: market-view-single
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/markets/{id}

        - id: market-delete
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/markets/delete/{id}

        - id: market-view-all
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/markets/all

        - id: market-update
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/markets/update/{id}

        - id: market-section-view-all
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/market-sections/all

        - id: market-section-update
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/market-sections/update/{id}

        - id: market-section-add
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/market-sections/add

        - id: shop-add
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/shops/add

        - id: shop-view-all
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/shops/all

        - id: shop-update
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/shops/update/{id}

        - id: states-all
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/states/all

        - id: lga-all
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/local-governments/all

        - id: council-wards-all
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/council-wards/all

        - id: Category-add
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/categories/add

        - id: Category-view-all
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/categories/all

        - id: Category-update
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/categories/update/{id}
#/api/products/all
        - id: all Products
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/products/all

        #/api/products/single
        - id: Single Products
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/products/{id}

    #/api/products/add
        - id: Single Products
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/products/add
              #Payment
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**


        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/ws-chat/**
eureka:
  client:
    hostname: localhost
    prefer-ip-address: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://41.78.80.108:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG