server:
  port: 8081  # Gateway's port
  address: 0.0.0.0

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable discovery-based routing
          lower-case-service-id: true

      routes:
<<<<<<< HEAD
        # Existing routes...
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**, /api/cart/**
=======
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**,/api/cart/**
>>>>>>> dev

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
        - id: logistics-service
          uri: lb://LOGISTICS-SERVICE
          predicates:
            - Path=/api/logistics/**

<<<<<<< HEAD
        # WebSocket and HTTP routes for chat service
        - id: chat-ws
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/ws-chat/**
          filters:
            - RewritePath=/ws-chat/(?<segment>.*), /$\{segment}

        - id: chat-service-http
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/chat/**
          filters:
            - RewritePath=/api/chat/(?<segment>.*), /api/chat/$\{segment}

        # Other existing services...
=======
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/ws/**

>>>>>>> dev
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**,/api/auth/**,/api/roles/**

        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/council-wards/**,/api/local-governments/**,/api/markets/**,/api/market-sections/**,/api/states/**,/api/statuses/**,/api/shops/**,/api/categories/**,/api/products/**

<<<<<<< HEAD
=======

>>>>>>> dev
eureka:
  client:
    hostname: localhost
    prefer-ip-address: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
