server:
  port: 8081  # Gateway's port
  address: 0.0.0.0

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable discovery-based routing
          lower-case-service-id: true

      routes:
        # Existing routes...
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**, /api/cart/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
        - id: logistics-service
          uri: lb://LOGISTICS-SERVICE
          predicates:
            - Path=/api/logistics/**

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/chat/**

        - id: chat-static
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1

        - id: chat-ws
          uri: lb:ws://CHAT-SERVICE
          predicates:
            - Path=/ws/**
        #          filters:
        #             - StripPrefix=1
        # WebSocket and HTTP routes for chat service

        # Other existing services...
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**,/api/auth/**,/api/roles/**

        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/council-wards/**,/api/local-governments/**,/api/markets/**,/api/market-sections/**,/api/states/**,/api/statuses/**,/api/shops/**,/api/categories/**,/api/products/**

eureka:
  client:
    hostname: localhost
    prefer-ip-address: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
